---
- group_by:
    key: architecture_{{ ansible_architecture }}

- group_by:
    key: system_{{ ansible_system }}
    parents:
      - architecture_{{ ansible_architecture }}

- group_by:
    key: os_family_{{ ansible_os_family }}
    parents:
      - system_{{ ansible_system }}

- group_by:
    key: distribution_{{ ansible_distribution }}
    parents:
      - os_family_{{ ansible_os_family }}
