
---
- name: Install baseline packages
  package:
    name: "{{ linux_package }}"
    state: present
  with_items: "{{ linux_packages }}"
  loop_control:
    loop_var: linux_package

- name: Update packages
  package:
    name: '*'
    state: latest
  when: linux_update
