
---
- name: Install baseline packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ common_packages_base }}"

- name: Update packages
  package:
    name: '*'
    state: latest
  when: common_packages_update
