---
- name: Register to RHS
  redhat_subscription:
    state: present
    username: "{{ rhs_username }}"
    password: "{{ rhs_password }}"
    autosubscribe: true
  when:
    - rhs_username is defined
    - rhs_password is defined
