---
- name: "Ensure state of subscription to RHN"
  redhat_subscription:
    org_id: "{{ linux_rhn_org_id }}"
    activationkey: "{{ linux_rhn_activation_key }}"
    autosubscribe: true
    state: present
  when:
    - linux_rhn_org_id is defined
    - linux_rhn_activation_key is defined

- name: "Configure state of repositories"
  command: subscription-manager repos --enable={{ linux_rhn_repo|quote }}
  with_items: "{{ linux_rhn_repos }}"
  loop_control:
    loop_var: linux_rhn_repo
