---
- name: Register to RHS
  redhat_subscription:
    state: present
    username: "{{ linux_rhs_username }}"
    password: "{{ linux_rhs_password }}"
    autosubscribe: true
  when:
    - linux_rhs_username is defined
    - linux_rhs_password is defined
