---
- name: "RHEL: Ensure state of subscription to RHN"
  redhat_subscription:
    org_id: "{{ linux_rhs_org_id }}"
    activationkey: "{{ linux_rhs_activation_key }}"
    autosubscribe: true
    state: present
  when:
    - linux_rhs_org_id is defined
    - linux_rhs_activation_key is defined


- name: "RHEL: Configure state of repositories"
  command: subscription-manager repos --enable={{ linux_rhs_repo|quote }}
  with_items: "{{ linux_rhs_repos }}"
  loop_control:
    loop_var: linux_rhs_repo
  when:
    - linux_rhs_org_id is defined
    - linux_rhs_activation_key is defined

- name: "EL: Ensure state of EPEL repository"
  yum_repository:
    name: epel
    description: EPEL YUM REPO
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    gpgcheck: no
    enabled: yes
    state: present

- name: "EL: Install baseline packages"
  yum:
    name: "{{ linux_package }}"
    state: present
  with_items: "{{ linux_packages }}"
  loop_control:
    loop_var: linux_package

- name: "EL: Update all packages"
  yum:
    name: '*'
    state: latest
  when: linux_update
