---
- import_tasks: defaults.yml

- name: "Process OS-specific"
  include_vars: "{{ linux_var_file }}"
  with_first_found:
    - files:
      - "{{ ansible_os_family }}.yml"
      skip: true
  loop_control:
    loop_var: linux_var_file
    label: "{{ linux_var_file }}"
  when: ansible_os_family != "RedHat"

- name: Include OS-specific variables (RedHat).
  include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
  when: ansible_os_family == "RedHat"
