- name: "yum: Install baseline packages"
  yum:
    name: "{{ linux_packages + linux_additional_packages }}"
    update_cache: yes
    state: present

- name: "yum: Update all packages"
  yum:
    name: '*'
    update_cache: yes
    state: latest
  when: linux_update
