- name: "EPEL repository"
  yum_repository:
    name: "{{ linux_repo.name }}"
    description: "{{ linux_repo.description }}"
    baseurl: "{{ linux_repo.baseurl }}"
    gpgcheck: "{{ linux_repo.gpgcheck }}"
    enabled: "{{ linux_repo.enabled }}"
    state: "{{ linux_repo.state }}"
  loop: "{{ linux_repos }}"
  loop_control:
    loop_var: linux_repo
    label: "{{ linux_repo.name }}"

- name: "yum: Install baseline packages"
  yum:
    name: "{{ linux_packages }}"
    state: present

- name: "yum: Update all packages"
  yum:
    name: '*'
    state: latest
  when: linux_update
