---
- name: "Ensure state of Red Hat subscription"
  redhat_subscription:
    username: "{{ linux_rhsm_username | default(omit) }}"
    password: "{{ linux_rhsm_password | default(omit) }}"
    activationkey: "{{ linux_rhsm_activation_key | default(omit) }}"
    org_id: "{{ linux_rhsm_org_id | default(omit) }}"
    state: "{{ linux_rhsm_state | default(omit) }}"
    autosubscribe: "{{ linux_rhsm_autosubscribe | default(omit) }}"
    consumer_name: "{{ linux_rhsm_consumer_hostname | default(omit) }}"

- name: "Ensure state of repository"
  rhsm_repository:
    name: "{{ linux_rhs_repo.name  | default(linux_rhs_repo) }}"
    state: "{{ linux_rhs_repo.state | default('present') }}"
  with_items: "{{ linux_rhs_repos + linux_additional_rhs_repos }}"
  loop_control:
    loop_var: linux_rhs_repo
